### ISSUE TITLE
Stronger authentication

### ISSUE THREAD

**Issue by m90** [offen/offen#424]
Operators currently log in using their email and a password. To protect usage data even better, additional measures can be taken.

## Approach: 2FA using a [TOTP](https://tools.ietf.org/html/rfc6238)

Using an app like Google Authenticator, Authy or a hardware token like a YubiKey, operators can enable 2-Factor-Authentication on their device.

- In the Admin console, operators enable 2FA for their login credentials
- Using a QR code or a text based code, operators add the account to the device they want to use for authenticating
- When logging in using credentials that are secured with a 2nd factor the TOTP will be requested in an intermediate screen after login

### Pros

- Well tested approach, lots of libraries around
- Apps and devices are easily available (Apps are free)

### Cons

- Adds another possibility of rendering an account inaccessible by losing access to the second factor device
- Offen has short lived login sessions, so operators would have to enter TOTPs often

**Comment by thelicato** [comment]
Is there any update on this?

**Comment by m90** [comment]
Thanks for checking in on this. I have to admit that while this would still be great to have, it's not on the top of the list. If anyone wants to pick it up in the meantime though, I'd be happy to help with getting such a feature merged and released.

**Comment by gbzret4d** [comment]
Why is this not planned? After all, the content is particularly worthy of protection

**Comment by m90** [comment]
This is solely a decision based on lack of resources. If you (or anyone else) wants to add this, I'm happy to reopen and do anything to support you with getting this merged.
