### ISSUE TITLE
"Offen Auditorium" on landing page is not working

### ISSUE THREAD

**Issue by tobimori** [offen/offen#445]
![image](https://user-images.githubusercontent.com/29142128/88149970-135b3700-cc01-11ea-8d46-791b3c0e1361.png)

**Comment by m90** [comment]
Do you have a URL for that? Also, in case it's not just an intermittent network issue, would it be possible to know about which call exactly failed for you (you can check the network tab in the dev tools)? It would also be interesting to know if you have opted in before seeing this.

Thanks!

**Comment by tobimori** [comment]
lol I'm stupid I should disable my adblocker

**Comment by m90** [comment]
Ok. That's interesting still as this should not do any shady stuff, and just do some same domain XHRs, so I am surprised there is blocking happening.

May I ask you which Adblocker you use in which browser and if you have any non-default settings in place?

**Comment by tobimori** [comment]
uBlock Origin and yes.

**Comment by m90** [comment]
Ok, so this is kind of not the smartest route uBlock is going here: apparently all `analytics.*` subdomains are being blocked (we run our own Offen on `analytics.offen.dev` when an Offen install that uses an `offen.*` subdomain (like I do on my personal website where it's `offen.frederikring.com`) does not get blocked.

The good part about the situation is that event collection also gets blocked which means we don't end up in a situation where someone that opted in will appear in the stats but is not able to manage their data, which would be kind of the worst case scenario.

We probably can't do much about this other than mention it in the docs and encourage people to use an `offen.*` subdomain.

**Comment by m90** [comment]
The updated docs are now included in v0.1.2 and we moved our own installation to `offen.offen.dev` so I am closing this. Thanks for making us aware of the issue.
