### ISSUE TITLE
Typos in database configuration documentation 

### ISSUE THREAD

**Issue by mlespiau** [offen/offen#467]
There is a typo in  https://docs.offen.dev/running-offen/configuring-the-application/#database. 
The sample configuration for mysql and postgres are both `OFFEN_DATABSE_CONNECTIONSTRING` when they should be `OFFEN_DATABASE_CONNECTIONSTRING`.

This dragged quite some time when configuring offen for the first time.

What really helped me figure it out was to use the offen debug command. I suggest that the documentation proposed to verify that the values are being properly set by running offen debug first. In my case I was running docker-compose so I was able to review the documention with a command like `docker-compose run offen debug`.

**Comment by m90** [comment]
> The sample configuration for mysql and postgres are both OFFEN_DATABSE_CONNECTIONSTRING when they should be OFFEN_DATABASE_CONNECTIONSTRING.

Oh no, this sounds like a terribly frustrating experience, I am sorry for that one. We'll fix it immediately.

Documenting that `debug` subcommand is a very good idea too. Thanks a lot for the valuable feedback.

**Comment by m90** [comment]
This is now fixed in the latest version of the docs:
- https://docs.offen.dev/running-offen/configuring-the-application/
- https://docs.offen.dev/running-offen/using-the-command/

Thanks for pointing us towards it!
