### ISSUE TITLE
Display non-rounded number on hover for totals

### ISSUE THREAD

**Issue by m90** [offen/offen#478]
When displaying a large number in the Auditorium (e.g. 3.456 sessions) this is currently shortened to `3.4k` which makes the UI less cluttered and noisy.

However, some users might still be interested in the actual number (i.e. 3.456). To cater for this need, we can put the number in the title attribute of the element holding the shortened value.

The relevant component is this one: https://github.com/offen/offen/blob/development/auditorium/src/views/components/auditorium/format.js

**Comment by kocvrek** [comment]
Hi, I would like to work on this issue.

**Comment by m90** [comment]
Sounds great @kocvrek let us know if there are any questions about it.

**Comment by kocvrek** [comment]
@m90 PR #483 is ready for review.

**Comment by m90** [comment]
Closed via #483
