### ISSUE TITLE
Auditorium UI: Emphasise weekends better

### ISSUE THREAD

**Issue by hendr-ik** [offen/offen#480]
This is the way we currently emphasise weekends in our Plotly bar charts - simple numbers, only slightly larger, italicized:
![bars is](https://offen.github.io/press-kit/offen-hacktoberfest/offen_bars_is.png)

We consider this not obvious enough and woud like to update it this way:
![bars want](https://offen.github.io/press-kit/offen-hacktoberfest/offen_bars_want.png)

Ideally it should be implemented directly in Plotly without extra css. The relevant component is this one:
[https://github.com/offen/offen/blob/master/auditorium/src/views/components/auditorium/chart.js](https://github.com/offen/offen/blob/master/auditorium/src/views/components/auditorium/chart.js)

**Comment by haridevelops** [comment]
Can I work on it ? If so please assign it to me.

**Comment by hendr-ik** [comment]
@haridevelops let me know if there are any questions

**Comment by prijeshb** [comment]
@hendr-ik  Should I take this, seems that no progress further by other person.

**Comment by m90** [comment]
Thanks @prijeshb , let's maybe check with @haridevelops if they still plan to work on this? Any input from your side?

**Comment by m90** [comment]
@prijeshb yeah, this will require some creative use of Plotly (negative bars maybe?) and is not something that is supported out of the box as-is. Maybe there is some other solution we don't know of yet?

Let me know if you want to work on this in any case so I can assign you. Thanks.

**Comment by haridevelops** [comment]
@hendr-ik 
I did look at the plotly documentation, we can provide bgcolor for all the ticks but again we need to go through all the logic that has ran for ticktext.
The way chart.js weekend logic is written, simple css fix would work right? (the `font-style: italic` is handled inline css only, we can replace with background-color css.)

**Comment by m90** [comment]
@haridevelops When I try applying a `background-color` to the span here: 

https://github.com/offen/offen/blob/05657130bbb1bd50fc06573514e021f699a710f1/auditorium/src/views/components/auditorium/chart.js#L60-L62

it doesn't really display any background for me. Is there something needed in addition to that?

**Comment by haridevelops** [comment]
@m90 I have locally up the code.
Plot is basically rendering SVG. The problem here is tspan tag. After research, i realise that tspan tag does not support background color. Refer here: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/tspan (there is no presentation attribute supporting background)

![image](https://user-images.githubusercontent.com/25661524/95658334-4560a300-0b37-11eb-918a-7d1d3d95e273.png)

I would like to recommend different aspect here emphasising weekend. Thoughts? 

![image](https://user-images.githubusercontent.com/25661524/95658470-41815080-0b38-11eb-9608-e202d68d9eaf.png)

**Comment by m90** [comment]
@haridevelops Thanks for doing that research. It's tricky business indeed.

> I would like to recommend different aspect here emphasising weekend. Thoughts?

Thing is we need to / want to comply with WACG 2.1 Accessibility Guidelines here, so styling this accordingly is a complicated topic. @hendr-ik is on holidays for a few more days, but I would suggest he follows up on this with you once he's back. Does this sound like a plan?

**Comment by haridevelops** [comment]
perfect @m90

**Comment by hendr-ik** [comment]
@haridevelops Thanks again for your efforts and the suggestion. Unfortunately, we cannot use green for highlighting because it is only used in connection with links in our UI. I think we need to dig deeper into Plotly and create a design that fits the possibilities.

**Comment by hendr-ik** [comment]
@haridevelops Please do not hesitate to submit your recommendation as a pull request in order to be officially recognized. Unfortunately, for the reasons mentioned above, we will not be able to merge it.
