### ISSUE TITLE
Visit duration

### ISSUE THREAD

**Issue by m90** [offen/offen#490]
Right now, Offen can only tell that a visit happened, but there is no way of telling if if this visit was an instant bounce or how much time the visitor has actually spent on the site.

In case we decided to implement such a feature in Offen (this is something that should be looked at from a privacy point of view separately), there would be multiple ways of doing it.

## Approach: using `navigator.sendBeacon`

Modern browsers expose the [`navigator.sendBeacon`][beacon] api that allows scripts to enqueue transmission of data on page unload. This would allow us to measure a delta between the event's creation date and an event's date of receipt. Almost every event could therefore be labeled with a `duration` value.

### Pros

- simple to implement
- duration data can be attached to the same event
- every event will have duration data

### Cons

- unclear how reliably it works
- users that would instantly visit the Auditorium after opting in would see an empty Auditorium as no data has been sent yet
- relies on the browser's time, which might not be what the server is using - resulting in incorrect values

[beacon]: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon

---

Open question: does the `sendBeacon` API allow for augmenting data on sending? This would allow us to gather correct data in the client without risking comparison of out-of-sync clocks.

## Approach: sending heartbeats

The client script receives the `EventID` used in the response to sending the initial event payload. It then sends so-called "hearbeats" to the server in a defined interval (10s?). This allows the server to record a heartbeat event which associates the `EventID` with a duration.

### Pros

- Allows users to instantly access this data

### Cons

- Additional outbound requests for the client
- This can generate a lot of data that needs to be synced down to clients
- Bounces will have no duration data at all
- Resolution of duration data is coarse

---

Alternatively, a mix of both approaches could be used: the initial event is sent instantly. Then `navigator.sendBeacon` is used to send the visit's duration once finished.

**Comment by m90** [comment]
An alternative and more privacy friendly approach to tracking the visit duration would be redefining what "bounce rate" means.

With a predefined bounce rate of 30s (this could be configurable), a pageview event could be marked as a bounce without having to record the exact duration of the visit.

**Comment by dillonr9** [comment]
In regards to the open question above, the [performance.now()](https://developer.mozilla.org/en-US/docs/Web/API/Performance/now) method looks like a viable avenue with sendBeacon.


Basing this on an interval seems to align philosophically ie. DOMHighResTimeStamp, quite privacy friendly. My concern with this approach would be the calling of the beforeunload event at the end, and the consistency across browsers.
