### ISSUE TITLE
"Bad gateway" when run behind a reverse proxy

### ISSUE THREAD

**Issue by DavidBernal** [offen/offen#510]
I know you recommended don't use a proxy, but I needed and I'm getting 502 when I go to my offen subdomain.

I setted OFFEN_SERVER_REVERSEPROXY=true but still failing.

Do I miss any option?

**Comment by DavidBernal** [comment]
My bad.

**Comment by m90** [comment]
Good to know you got it working.

Just for the record and in case someone else finds this issue: setting `OFFEN_SERVER_REVERSEPROXY` is not a hard requirement for running Offen behind a reverse proxy, it just disables some features that would not make too much sense when run behind a proxy (e.g. access logs). Offen can always run behind a reverse proxy, no matter the configuration.
