### ISSUE TITLE
Issues with SSL Cert on Nginx Reverse Proxy

### ISSUE THREAD

**Issue by Quin452** [offen/offen#718]
Carrying on from [this tweet](https://twitter.com/hioffen/status/1534072957147963394), I believe I have AutoTLS enabled in the config file, but I control the certificates on the host machine/hypervsior (for some reason, Certbot won't work on guest machines properly).

> I'm looking at trying out Offen on a virtual server, using Nginx reverse proxy.  The install steps were fine, however, I am having issue with loading the site (just redirects to the IP) and the SSL certificates ("SSL_ERROR_INTERNAL_ERROR_ALERT").

**Comment by m90** [comment]
I am still not entirely sure I understand your setup correctly, so I'll just ask a few more questions:

- which domain are you planning to run your Offen instance on and are you able to acquire a SSL certificate for that domain (or a wildcard one for the top level domain) without using the AutoTLS feature? Are you already doing that and if yes, by which means?
- how do you run Offen? (e.g. Docker / systemd / something else)
- in your configuration for Offen, do you set any of `OFFEN_SERVER_AUTOTLS`, `OFFEN_SERVER_SSLKEY`, `OFFEN_SERVER_SSLCERTIFICATE`, `OFFEN_SERVER_REVERSEPROXY`?

**Comment by Quin452** [comment]
Hi, thanks for getting back.

- I run Certbot on the host machine.  Certbot picks up the site-enabled config file, and it validates against offen.classicniall.co.uk
- Offen is ran on a guest machine/virtual server.  Essentially bare metal Ubuntu 20.04 install, using the Systemd install instructions given.
- I have set OFFEN_SERVER_AUTOTLS to the subdomain above, and that's it.

Update: I removed/commented out the autotls and now I get a 502.  So some progress :-)

**Comment by m90** [comment]
`OFFEN_SERVER_AUTOTLS` is not a Boolean flag, instead it expects you to pass the domains: https://docs.offen.dev/running-offen/configuring-the-application/#offen_server_autotls

As you acquire the certificates using Certbot I would think you have two options now:

1. pass the certificate and key files to Offen using `OFFEN_SERVER_SSLCERTIFICATE` and `OFFEN_SERVER_SSLCERTIFICATE`
2. terminate SSL at nginx level using the certs acquired by certbot (you are running nginx right?) and just `reverse_proxy` to whichever port you are running Offen on

Option 2 is probably the easiest as otherwise you'll need to configure nginx to act as a TCP proxy which can be hairy.

**Comment by Quin452** [comment]
Aye, I think option 2 is what I'm trying to achieve.
On the host machine, I have various virtual machines.  I use Nginx Reverse Proxy on the host machine, and run Certbot on that.
That does generate the certificates (i.e. there is a certificate for Offen and one for my Apache guest machine, as well as many others).

As I mentioned earlier, I removed the OFFEN_SERVER_AUTOTLS from the config, and now it loads 502.

**Comment by m90** [comment]
It's hard for me to tell like this and I feel this might not necessarily be related to Offen, but this is what I'd do to debug this:

- check if the Offen process is actually running
- check if the Offen process logs anything suspicious
- check if the Offen process is running on the expected port and hostname (i.e. matches your nginx config)
- check if you can reach Offen from within your local network (however that might look like in detail), e.g. if you are bound to the default port of 3000, run `curl http://localhost:3000/healthz` and see if you get a proper response

**Comment by Quin452** [comment]
```
● offen.service - Offen Web Analytics
     Loaded: loaded (/lib/systemd/system/offen.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2022-06-07 11:43:37 UTC; 2min 21s ago
   Main PID: 650 (offen)
      Tasks: 6 (limit: 1066)
     Memory: 23.6M
     CGroup: /system.slice/offen.service
             └─650 /usr/local/bin/offen

Jun 07 11:43:37 offen systemd[1]: Started Offen Web Analytics.
Jun 07 11:43:37 offen offen[650]: time="2022-06-07T11:43:37Z" level=info msg="Successfully applied database migrations"
Jun 07 11:43:38 offen offen[650]: time="2022-06-07T11:43:38Z" level=info msg="Server now listening on port 3000"
Jun 07 11:43:38 offen offen[650]: time="2022-06-07T11:43:38Z" level=info msg="Cron successfully pruned expired events" removed=0
```

I noticed a TLS handshake error in the error log, so I rebooted it just a few minutes ago to check:
```
Jun 06 15:06:28 offen offen[663]: 2022/06/06 15:06:28 http: TLS handshake error from 192.168.1.23:50217: acme/autocert: missing server name
Jun 06 15:51:35 offen offen[663]: time="2022-06-06T15:51:35Z" level=info msg="Cron successfully pruned expired events" removed=0
Jun 06 16:51:35 offen offen[663]: time="2022-06-06T16:51:35Z" level=info msg="Cron successfully pruned expired events" removed=0
Jun 06 17:51:35 offen offen[663]: time="2022-06-06T17:51:35Z" level=info msg="Cron successfully pruned expired events" removed=0
Jun 06 18:51:35 offen offen[663]: time="2022-06-06T18:51:35Z" level=info msg="Cron successfully pruned expired events" removed=0
Jun 06 19:51:35 offen offen[663]: time="2022-06-06T19:51:35Z" level=info msg="Cron successfully pruned expired events" removed=0
Jun 06 20:51:35 offen offen[663]: time="2022-06-06T20:51:35Z" level=info msg="Cron successfully pruned expired events" removed=0
Jun 06 21:51:35 offen offen[663]: time="2022-06-06T21:51:35Z" level=info msg="Cron successfully pruned expired events" removed=0
Jun 06 22:51:35 offen offen[663]: time="2022-06-06T22:51:35Z" level=info msg="Cron successfully pruned expired events" removed=0
Jun 06 23:51:35 offen offen[663]: time="2022-06-06T23:51:35Z" level=info msg="Cron successfully pruned expired events" removed=0
Jun 07 00:51:35 offen offen[663]: time="2022-06-07T00:51:35Z" level=info msg="Cron successfully pruned expired events" removed=0
Jun 07 01:51:35 offen offen[663]: time="2022-06-07T01:51:35Z" level=info msg="Cron successfully pruned expired events" removed=0
Jun 07 02:51:35 offen offen[663]: time="2022-06-07T02:51:35Z" level=info msg="Cron successfully pruned expired events" removed=0
Jun 07 03:51:35 offen offen[663]: time="2022-06-07T03:51:35Z" level=info msg="Cron successfully pruned expired events" removed=0
Jun 07 04:51:35 offen offen[663]: time="2022-06-07T04:51:35Z" level=info msg="Cron successfully pruned expired events" removed=0
Jun 07 05:51:35 offen offen[663]: time="2022-06-07T05:51:35Z" level=info msg="Cron successfully pruned expired events" removed=0
Jun 07 06:51:35 offen offen[663]: time="2022-06-07T06:51:35Z" level=info msg="Cron successfully pruned expired events" removed=0
Jun 07 07:51:35 offen offen[663]: time="2022-06-07T07:51:35Z" level=info msg="Cron successfully pruned expired events" removed=0
Jun 07 08:38:25 offen offen[663]: 2022/06/07 08:38:25 http: TLS handshake error from 192.168.1.23:51999: acme/autocert: missing server name
Jun 07 08:51:35 offen offen[663]: time="2022-06-07T08:51:35Z" level=info msg="Cron successfully pruned expired events" removed=0
Jun 07 09:00:53 offen offen[663]: time="2022-06-07T09:00:53Z" level=info msg="Gracefully shut down server"
Jun 07 09:00:53 offen systemd[1]: Stopping Offen Web Analytics...
Jun 07 09:00:53 offen systemd[1]: offen.service: Succeeded.
Jun 07 09:00:53 offen systemd[1]: Stopped Offen Web Analytics.
Jun 07 09:00:53 offen systemd[1]: Started Offen Web Analytics.
Jun 07 09:00:53 offen offen[4470]: time="2022-06-07T09:00:53Z" level=info msg="Successfully applied database migrations"
Jun 07 09:00:53 offen offen[4470]: time="2022-06-07T09:00:53Z" level=info msg="Server now listening on port 3000"
Jun 07 09:00:53 offen offen[4470]: time="2022-06-07T09:00:53Z" level=info msg="Cron successfully pruned expired events" removed=0
Jun 07 10:00:53 offen offen[4470]: time="2022-06-07T10:00:53Z" level=info msg="Cron successfully pruned expired events" removed=0
Jun 07 11:00:53 offen offen[4470]: time="2022-06-07T11:00:53Z" level=info msg="Cron successfully pruned expired events" removed=0
Jun 07 11:42:54 offen offen[4470]: time="2022-06-07T11:42:54Z" level=info msg="Gracefully shut down server"
Jun 07 11:42:54 offen systemd[1]: Stopping Offen Web Analytics...
Jun 07 11:42:54 offen systemd[1]: offen.service: Succeeded.
Jun 07 11:42:54 offen systemd[1]: Stopped Offen Web Analytics.
-- Reboot --
Jun 07 11:43:37 offen systemd[1]: Started Offen Web Analytics.
Jun 07 11:43:37 offen offen[650]: time="2022-06-07T11:43:37Z" level=info msg="Successfully applied database migrations"
Jun 07 11:43:38 offen offen[650]: time="2022-06-07T11:43:38Z" level=info msg="Server now listening on port 3000"
Jun 07 11:43:38 offen offen[650]: time="2022-06-07T11:43:38Z" level=info msg="Cron successfully pruned expired events" removed=0
```

I've just left the reverse proxy as default 80/443 (going off the guide), and I can access it just fine via SSH, but not with the IP (URL/subdomain is 502).

**Comment by Quin452** [comment]
Am I to assume that Offen installs all the needed packages using the Systemd method?  Or am I to install packages (LAMP, Nginx, etc.)?

**Comment by m90** [comment]
> I've just left the reverse proxy as default 80/443 (going off the guide),

I don't understand what that means? Which proxy in which guide are you referring to?

When it comes to configuring Offen, you can do one of two things:
- run Offen using AutoTLS, which means it will listen on port 80 and 443
- run Offen without AutoTLS which means it will listen on the configured port (3000 as the default)

You want to do the latter, so your `reverse_proxy` directive in the nginx config should be pointing to `<hostname>:3000`. I don't know which additional layers are in between nginx and Offen in your case, but in case all of them allow traffic on port 3000, nginx should be able to route traffic to your running service.

**Comment by Quin452** [comment]
I was talking about [this guide](https://docs.offen.dev/running-offen/tutorials/configuring-deploying-offen-ubuntu/).

Thanks for the explanation.  Without AutoTLS, and with the certs handled by the Host machine, all I needed to do is add port 3000 to the Reverse Proxy IP, and the site loads :-)

There was no clear instructions as to what to do with reverse proxy from the Docs, but it's been cleared up now :-)
