### ISSUE TITLE
Question: New to Analytics; how does Campaigns and Sources work?

### ISSUE THREAD

**Issue by Quin452** [offen/offen#719]
So far, I am enjoying Offen.  I can see the data coming through, and it makes sense.

However, I am relatively new to Analytics, and was wondering, how Campaigns and Sources are populated ("_No data available for this view._")
I'm assuming that Referrals means "from where they came", it _None_ is when they've visited directly.

Also, what is Weekly Retention?  Is that to do with how many people revisit the site?

**Comment by m90** [comment]
Usage of campaigns and sources is documented here: https://docs.offen.dev/running-offen/campaigns-sources/

You are right about weekly retention, it shows you how many users are returning over the course of four weeks, also see: https://docs.offen.dev/running-offen/metrics-explained/#weekly-retention
