### ISSUE TITLE
Is visual tracking against privacy?

### ISSUE THREAD

**Issue by Quin452** [offen/offen#725]
Hi

Just a question about visual tracking/heatmaps/hotjar/etc.  Is this against privacy?

If so, how?  I've seen a few articles about this, but nothing explaining how.

**Comment by m90** [comment]
Privacy is not a term that is too well defined, so this will be a subjective take.

I'd argue that all tracking is against privacy, always. If you want perfect privacy for your users, mute your server logs and remove all analytics software of all kinds. However, sometimes this is not a feasible scenario so it's about making tradeoffs. Building Offen we selected a subset of data that seems to be a good compromise between being useful and still respecting user privacy. Visual tracking is not something we'll ever do as for us, it's not justifiable to collect a lot of data that is unique to a certain user when you compare it to the insights it can give operators.

That being said, one thing all tracking ever should be doing is: do not use 3rd party services, it's just never ok to share such data with others (no matter the TOS) and it's also not needed.
