### ISSUE TITLE
Chrome Extension issue

### ISSUE THREAD

**Issue by SoftCreatR** [offen/offen#745]
The CRX can't be installed:

![image](https://user-images.githubusercontent.com/81188/191350585-4e7cee36-d1c2-415f-a545-53d442148a1e.png)

Installing it as unpackaged extension works, however, there is still the display issue mentioned earlier:

![image](https://user-images.githubusercontent.com/81188/191351620-7ac7f28e-f988-4e25-b778-955ceffa2d5c.png)

But besides, everything works fine now.

**Comment by m90** [comment]
> The CRX can't be installed:

This is mentioned in the docs, you will need to right click download and then drag the file onto the browser. This is complicated, but there seems to be no easy way around it.

I cannot repro that display issue in any way. Any hints about anything special in your setup?

**Comment by SoftCreatR** [comment]
> This is mentioned in the docs, you will need to right click download and then drag the file onto the browser.

That's what I did ;) However, if I drag & drop it into the extensions page (chrome://extensions), it seems to install, but it is disabled for security reasons:

![image](https://user-images.githubusercontent.com/81188/191353192-a196ab2b-bd1e-4ee5-b26c-ca6f8c42a708.png)

> but there seems to be no easy way around it

Why not publish it in the Chrome Web Store?

> Any hints about anything special in your setup?

Nothing special, I think.

**Comment by SoftCreatR** [comment]
I guess the problem is 

```css
.popup-mw {
  max-width: 24rem;
}
```

in fix.css. Instead of `max-width`, this should be just `width`, or

```css
.popup-mw {
    max-width: 24rem;
    width: max-content;
}
```

=>

![image](https://user-images.githubusercontent.com/81188/191354794-19156991-4d9e-4583-8670-94a26923ddda.png)

**Comment by m90** [comment]
> Why not publish it in the Chrome Web Store?

The Chrome Web Store does not accept extension using Manifest V2 anymore. As mentioned earlier, Manifest V3 does not work in Firefox at the moment, so we're being crushed by politics here. As long as we want to maintain a single codebase and support both Firefox and Chrome, we'll need to use Manifest V2, limiting ourselves to distributing the CRX like this. I know it sucks, but we simply don't have the resources to participate in this Google initiated rat race. Once Firefox supports V3 as well, we can migrate (which isn't too hard from what I have read). Until then we'll have to live with some crutch. See: https://blog.mozilla.org/addons/2022/05/18/manifest-v3-in-firefox-recap-next-steps/

Thanks for the pointers about the styling, maybe @hendr-ik can look into this?

**Comment by SoftCreatR** [comment]
Other sightings:

In Chrome, the links within the popup aren't working. Clicking on them does nothing. However, right-click -> Open in new tab/window works.

**Comment by hendr-ik** [comment]
Thanks @SoftCreatR - I can reproduce the issues in Chrome and the suggested fix works well :v:

**Comment by m90** [comment]
Apart from the ugly Chrome installation all of this has been adressed in v1.3.2. Thanks for the input.
