### ISSUE TITLE
Cannot invite user to "share all accounts"

### ISSUE THREAD

**Issue by Quin452** [offen/offen#752]
Within the Admin Console, I enter in my employee email address so they can have access to all accounts (all the websites that we use Offen to track).

It then prompts me to enter my credentials to verify, and then this is loaded:
![firefox_f4oz90moKc](https://user-images.githubusercontent.com/8374397/203384116-ecc3dbd8-8526-4ee3-8033-81bc404d8262.png)

((you can see where I host Offen))

This happened on 1.1.0 as well as 1.3.3 (I've just updated it).

**Comment by m90** [comment]
This looks as if the SMTP credentials you are providing are not recognized by the target SMTP server.

Can you confirm that you are setting `OFFEN_SMTP_USER` and `OFFEN_SMTP_PASSWORD` to valid values and that your running process is picking these up correctly?

If you can confirm that the values are correct, can you use the [`offen debug` ](https://docs.offen.dev/running-offen/using-the-command/#offen-debug)command to check whether the application picks them up correctly as well?

**Comment by m90** [comment]
I assume this issue can be closed. If you need further support with this, feel free to reopen.
