### ISSUE TITLE
Display data on the site

### ISSUE THREAD

**Issue by Quin452** [offen/offen#770]
Hi
I was wondering if there is a way to display a site's analytics on the site itself, rather than having to go to Offen and sign in, etc.

The easiest way to explain it is showing the site's data on the WP-Admin dashboard (but I am not using WordPress).

In essence, I'd set up an account in my install of Offen (this can be for my own sites, or my clients' sites) and then that data can be seen on the website.
This isn't the user's data.

**Comment by m90** [comment]
No, that's not supported and I'd also think it's not something we want to do. Usage data should be handled confidential even if it's "just" aggregated statistics, so having it behind a login always seems reasonable to me right now.

**Comment by Quin452** [comment]
So how can a site owner see their analytical data for their site?

**Comment by m90** [comment]
The feature that is supposed to used here is sharing a single account from within the Auditorium:

![image](https://user-images.githubusercontent.com/1662740/213515201-38db4263-a8e4-43b6-b6f9-1cd1bd778397.png)

This will send out instructions on how to create a login to the email you supply, allowing access to that account only (unless you have already granted access to other accounts before).
