### ISSUE TITLE
Offen + Nginx Proxy Manager

### ISSUE THREAD

**Issue by philharmonie** [offen/offen#778]
I ran offen without specifying ports, I added offen to my npm network and added a host for offen:80 and I applied a SSL certificate.

When I now access `https://mydomain.com/login` I get an error that too many redirects occur. When I change my host to offen:443, I get the error, that an HTTP client tries to connect to HTTPS.

How can I run offen behind npm?

**Comment by m90** [comment]
> and I applied a SSL certificate.

How exactly did you do this? Do you plan to terminate SSL at nginx level or do you use nginx as a TCP proxy and have Offen terminate SSL?

**Comment by philharmonie** [comment]
I'd prefer to use the certificates created by npm. When creating a new host, I create the SSL certificate with the host creation using npm.

**Comment by m90** [comment]
In that case, when not setting configuration for either SSL or a port, the default port is `3000` (see https://docs.offen.dev/running-offen/configuring-the-application/#http-server), which means your proxy target should likely be `offen:3000`?

**Comment by philharmonie** [comment]
With that I get `502 Bad Gateway`

**Comment by m90** [comment]
You will need to provide more information about your configuration and setup. Like this, it's hard to tell.

**Comment by philharmonie** [comment]
I found `https://hub.docker.com/r/offen/offen` and followed the steps there:
```
docker volume create offen_data
docker volume create offen_certs
mkdir offen
touch offen/offen.env

docker run -it --rm \
  -v offen_data:/var/opt/offen \
  -v offen_certs:/var/www/.cache \
  -v offen/offen.env:/etc/offen/offen.env \
  offen/offen:latest setup \
  -email my@mail.com \
  -name mysite \
  -populate

docker run -d \
  --name offen \
  -v offen_data:/var/opt/offen \
  -v offen_certs:/var/www/.cache \
  -v offen/offen.env:/etc/offen/offen.env \
  offen/offen:latest
```

Then I went to npm GUI, added the now host (trying ports 80, 443 and now 3000). That all I did.

**Comment by m90** [comment]
This looks correct. If you now place a service in the same Docker network, this service (nginx proxy manager in your case), it will be able to connect to `offen:3000`.

If you do not run your proxy in Docker, and need to use host networking, you will also need to expose port 3000 by passing `-p 3000:3000`  to your command. Be aware though that this will also open port 3000 on your host firewall, so using Docker networking is preferred.

**Comment by philharmonie** [comment]
My ports 80 and 443 are already blocked by npm. I don't expose and I don't want to open any other port. That's why I prefer docker networking, as well.

Inside my npm container:
```
[root@docker-762f3be33c39:/app]# curl offen:3000
curl: (7) Failed to connect to offen port 3000: Connection refused
[root@docker-762f3be33c39:/app]# ping offen
PING offen (172.27.0.7) 56(84) bytes of data.
64 bytes from offen.npm (172.27.0.7): icmp_seq=1 ttl=64 time=0.963 ms
64 bytes from offen.npm (172.27.0.7): icmp_seq=2 ttl=64 time=0.132 ms
64 bytes from offen.npm (172.27.0.7): icmp_seq=3 ttl=64 time=0.136 ms
```

**Comment by m90** [comment]
What's the log output of your Offen container when starting up. It should tell you about the port it's listening on.

**Comment by philharmonie** [comment]
```
time="2023-02-21T09:59:28Z" level=warning msg="SMTP for transactional email is not configured right now, mail delivery will be unreliable"
time="2023-02-21T09:59:28Z" level=warning msg="Refer to the documentation to find out how to configure SMTP"
time="2023-02-21T09:59:28Z" level=info msg="Successfully applied database migrations"
time="2023-02-21T09:59:28Z" level=info msg="Server now listening on port 80 and 443 using AutoTLS"
time="2023-02-21T09:59:28Z" level=info msg="Cron successfully pruned expired events" removed=0
```

**Comment by m90** [comment]
This means that somehow your instance thinks you want to use SSL termination at that level, which means you likely set some TLS related option, not sure why.

What you want instead, is using plain HTTP. You can check the docs on how to configure it like this https://docs.offen.dev/running-offen/configuring-the-application/ - it's probably just about removing configuration options you don't need.

**Comment by philharmonie** [comment]
The only config I added was `OFFEN_SERVER_AUTOTLS="offen.mysite.com"`. I removed it and now get `Server now listening on port 80` in the logs.
Still offen:80 or offen:3000 show me "502 Bad Gateway". No additional logs in docker logs.

**Comment by m90** [comment]
I forgot that the Docker image will listen to port 80 by default. From the linked docs

> The Docker image sets this value to 80 in the Dockerfile, so you cannot override it from within an env file. Instead, map port 80 in the container to the desired port on your host system.

In any case, this sounds as if your Offen container is now ready to accept HTTP, so the Bad Gateway is probably some connectivity / networking issue with your proxy setup. You could try verifying this by exposing a port to your host (i.e. `-p 3000:80` and see if `localhost:3000` answers).

If you still think this is an issue with Offen, please provide a reproducible example for me to have a look at.

**Comment by philharmonie** [comment]
My issue is reproducible and as I typed the steps, I found the final problem. First was to add the `OFFEN_SERVER_AUTOTLS="..."`, that is not required. 2nd and final issue: I removed the container for the tests and I found out that with that (for sure) it is not connected to my npm network anymore. Adding it back, the UI shows up. Thank you very much for your help.
