### ISSUE TITLE
Android 、iOS And Flutter access 

### ISSUE THREAD

**Issue by Jengro777** [offen/offen#787]
Does it support original client access? If supported, how can I access it? No relevant documents found

**Comment by m90** [comment]
> original client access

Could you elaborate on what exactly you refer to by this term? Is it about non-browser clients?

**Comment by Jengro777** [comment]
> > original client access
> 
> Could you elaborate on what exactly you refer to by this term? Is it about non-browser clients?

yes

**Comment by m90** [comment]
This is currently not supported. Adding this would require a substantial amount of work, which I am not sure we'll find the resources to put into.
