### ISSUE TITLE
Auditorium first login crash

### ISSUE THREAD

**Issue by codechanger0** [offen/offen#814]
I am trying to login to Auditorium for the first time after completing the setup on Ubuntu. However, I am getting this error
![image](https://github.com/offen/offen/assets/115946408/ee3446de-75b5-4ca0-9406-223b410b73e9)
On the console, I have found this error
![image](https://github.com/offen/offen/assets/115946408/39fb186a-daca-48ef-9733-7a3de51bb443)

The installation method I tried was direct installation on Ubuntu. After starting and verifying systemctl service status, I went ahead to directly access the port in combination as IP_ADDRESS:PORT/setup. The IP_Address is an address of virtual machine and port I used was 3000. After filling the mail, password informations, I was able to setup the account. 
Not sure what can be the issue here.

**Comment by m90** [comment]
Do you try to access the Auditorium using `http`?  Offen needs a "secure context" so you either have to use HTTPS or `localhost`. Other custom domains that are served via http are not supported properly.

In case your instance is available on the public internet, you can have Offen autogenerate SSL certificates for you https://docs.offen.dev/running-offen/tutorials/configuring-deploying-offen-ubuntu/#setting-up-autotls

Also see https://docs.offen.dev/running-offen/installation-requirements/#serving-the-application-via-https

**Comment by codechanger0** [comment]
Yes. I am using http not https, because I am accessing my VM via IP address, not a domain name. My site is hosted via GitLab pages, and I am setting up offen on a DigitalOcean VM. So two different machines/VM are involved.  
The site is already having an SSL certificate which is provisioned and renewed by GitLab automatically. So I believe using offen for SSL certificate will create an issue.

Any tips on how to setup the two of them is much appreciated.

**Comment by m90** [comment]
Assuming you run `www.yoursite.com` on GitLab pages with a GitLab pages provisioned certificate, there is no reason not to have Offen running on your VM and reachable as `offen.yoursite.com` acquire a certificate for that very domain. In case you plan to run multiple applications on your VM, you can also have your proxy (e.g. Caddy or nginx) acquire the certficates for you (https://docs.offen.dev/running-offen/installation-requirements/#running-the-application-behind-a-reverse-proxy)

This might also be helpful for you https://docs.offen.dev/running-offen/setting-up-using-subdomains/

**Comment by m90** [comment]
Closing this as stale. Feel free to reopen in case you need further support.
