### ISSUE TITLE
Proposal: Replace go-mail/mail with wneesen/go-mail

### ISSUE THREAD

**Issue by wneessen** [offen/offen#817]
I noticed that the offen server is using the [go-mail/mail](https://github.com/go-mail/mail) library for sending mails. This library is not actively maintained anymore and hasn't seen an update in 5+ years. 

I personally [maintain a library](https://github.com/go-mail/mail) that is still actively maintained and is very similar to go-mail/mail, but follows idiomatic Go style and best practice. It also supports sendmail support out of the box. My question is, would there be interest in replacing the currently used library? in that case I could provide a PR.

**Comment by m90** [comment]
Thanks for proposing this. I also noticed that go-mail is abandoned at some point but wasn't really sure what to replace it with. In case you want to provide a PR, that'd be very welcome, yes. Thanks :tophat:

**Comment by m90** [comment]
I'm planning to cut a release in the next month or so. In case you would still like to work on this, please lmk and I can include it accordingly. No pressure though.

**Comment by wneessen** [comment]
Thanks for the update. I had too many issues getting the DEV environment running, which kept me from investing much time into this yet, but I saw the update in the other ticket, that you fixed something there as well. I'll give it a try again in the next days and if it works, will work on this patch accordingly.

**Comment by wneessen** [comment]
I'd like some input from you. Due to the way the SMTP Client in go-mail works, the `New()` returns a `Client` pointer and possible error. I know that's uncommon for a `New` constructor but it is what we went for when the lib was built and cannot be changed anymore.

In https://github.com/offen/offen/blob/development/server/mailer/smtpmailer/smtpmailer.go#L12 yet there is currently no error handling. What would you propose in this case? Introduce error handling (which would involve more changes than just the mailer) or going a different route? You recommendation is appreciated.

**Comment by m90** [comment]
I think it'd be fine to change the signature of `smtpmailer.New` to return `mailer.Mailer, error`. The error will then need to propagate up to `main.cmdServe` and `main.cmdDemo` which exit 1 in case an error is being returned.

Does that make sense to you?
