### ISSUE TITLE
Text displayed as "[object Object]"

### ISSUE THREAD

**Issue by tobru** [offen/offen#839]
The answer to "How can I review and delete my usage data or opt out?" is displayed as "[object Object]":

![Screenshot_20240519_101417](https://github.com/offen/offen/assets/1695957/e6b165c8-4411-4857-bbf4-6377c77b264b)

**Comment by m90** [comment]
What's your version and what locale settings do you use? Are there any errors in your console? Does this also happen on offen.offen.dev for you? I can't really reproduce and it's a bit mysterious as all other strings are displayed correctly, using the same mechanism.

**Comment by tobru** [comment]
> What's your version and what locale settings do you use?

It's version 1.4.1, and it happens in every locale.

> Are there any errors in your console?

No errors are shown in the console.

> Does this also happen on offen.offen.dev for you?

Yes, the same issue happens there.

I just discovered that this only happens on Firefox, not on Chromium. I'm currently on Firefox 126.0 (64-bit) on Arch Linux.

**Comment by tobru** [comment]
Oh, now I see it on Chromium as well. It didn't show up when I deleted the cookie, once I opted in again, this strange text appears.

**Comment by m90** [comment]
This was introduced in #830 and is fixed in #840

**Comment by m90** [comment]
This is fixed in [v1.4.2](https://github.com/offen/offen/releases/tag/v1.4.2)
